const express=require('express');const path=require('path');const fs=require('fs');const crypto=require('crypto');const bcrypt=require('bcryptjs');const jwt=require('jsonwebtoken');
const app=express();const PORT=Number(process.env.PORT)||3000;const SECRET=process.env.JWT_SECRET||'levaren-change-this-secret';const DB=path.join(__dirname,'data');const USERS=path.join(DB,'users.json');const ORDERS=path.join(DB,'orders.json');
fs.mkdirSync(DB,{recursive:true});for(const f of [USERS,ORDERS])if(!fs.existsSync(f))fs.writeFileSync(f,'[]');
app.use(express.json({limit:'1mb'}));app.use(express.static(path.join(__dirname,'public')));
const read=f=>{try{return JSON.parse(fs.readFileSync(f,'utf8'))}catch{return[]}};const write=(f,d)=>fs.writeFileSync(f,JSON.stringify(d,null,2));
const pub=u=>({id:u.id,name:u.name,email:u.email,phone:u.phone||'',addresses:u.addresses||[],settings:u.settings||{theme:'system',notifications:true}});
function auth(req,res,next){const t=(req.headers.authorization||'').replace(/^Bearer\s+/i,'');try{req.user=jwt.verify(t,SECRET);next()}catch{res.status(401).json({error:'Oturum gerekli.'})}}
app.get('/api/health',(req,res)=>res.json({ok:true,service:'levaren'}));
app.post('/api/register',async(req,res)=>{const{name,email,password}=req.body||{};if(!name?.trim()||!email?.trim()||!password||password.length<6)return res.status(400).json({error:'Ad, e-posta ve en az 6 karakterli şifre gerekli.'});const users=read(USERS),mail=email.trim().toLowerCase();if(users.some(u=>u.email===mail))return res.status(409).json({error:'Bu e-posta zaten kayıtlı.'});const u={id:crypto.randomUUID(),name:name.trim(),email:mail,password:await bcrypt.hash(password,10),phone:'',addresses:[],settings:{theme:'system',notifications:true}};users.push(u);write(USERS,users);res.json({token:jwt.sign({id:u.id},SECRET,{expiresIn:'30d'}),user:pub(u)})});
app.post('/api/login',async(req,res)=>{const users=read(USERS),email=String(req.body?.email||'').trim().toLowerCase(),password=String(req.body?.password||''),u=users.find(x=>x.email===email);if(!u||!(await bcrypt.compare(password,u.password)))return res.status(401).json({error:'E-posta veya şifre hatalı.'});res.json({token:jwt.sign({id:u.id},SECRET,{expiresIn:'30d'}),user:pub(u)})});
app.get('/api/me',auth,(req,res)=>{const u=read(USERS).find(x=>x.id===req.user.id);u?res.json(pub(u)):res.status(404).json({error:'Kullanıcı bulunamadı.'})});
app.put('/api/me',auth,(req,res)=>{const users=read(USERS),i=users.findIndex(x=>x.id===req.user.id);if(i<0)return res.status(404).json({error:'Kullanıcı bulunamadı.'});const{name,phone,settings,addresses}=req.body||{};if(name!==undefined)users[i].name=String(name).trim();if(phone!==undefined)users[i].phone=String(phone).trim();if(settings)users[i].settings={...users[i].settings,...settings};if(Array.isArray(addresses))users[i].addresses=addresses.map(String);write(USERS,users);res.json(pub(users[i]))});
app.post('/api/change-password',auth,async(req,res)=>{const{currentPassword,newPassword}=req.body||{};if(!newPassword||newPassword.length<6)return res.status(400).json({error:'Yeni şifre en az 6 karakter olmalı.'});const users=read(USERS),i=users.findIndex(x=>x.id===req.user.id);if(i<0||!(await bcrypt.compare(currentPassword||'',users[i].password)))return res.status(400).json({error:'Mevcut şifre hatalı.'});users[i].password=await bcrypt.hash(newPassword,10);write(USERS,users);res.json({ok:true})});
app.get('/api/orders',auth,(req,res)=>res.json(read(ORDERS).filter(o=>o.userId===req.user.id).sort((a,b)=>b.createdAt-a.createdAt)));
app.post('/api/orders',auth,(req,res)=>{const{items,total,address}=req.body||{};if(!Array.isArray(items)||!items.length||!address?.trim())return res.status(400).json({error:'Ürünler ve teslimat adresi gerekli.'});const orders=read(ORDERS),o={id:'LV-'+Date.now().toString(36).toUpperCase(),userId:req.user.id,items,total:Number(total)||0,address:address.trim(),status:'Hazırlanıyor',createdAt:Date.now()};orders.push(o);write(ORDERS,orders);res.status(201).json(o)});
app.post('/api/orders/:id/cancel',auth,(req,res)=>{const a=read(ORDERS),i=a.findIndex(o=>o.id===req.params.id&&o.userId===req.user.id);if(i<0)return res.status(404).json({error:'Sipariş bulunamadı.'});if(a[i].status!=='Hazırlanıyor')return res.status(400).json({error:'Bu sipariş artık iptal edilemez.'});a[i].status='İptal edildi';write(ORDERS,a);res.json(a[i])});
app.post('/api/orders/:id/return',auth,(req,res)=>{const a=read(ORDERS),i=a.findIndex(o=>o.id===req.params.id&&o.userId===req.user.id);if(i<0)return res.status(404).json({error:'Sipariş bulunamadı.'});if(a[i].status!=='Teslim edildi')return res.status(400).json({error:'İade talebi yalnızca teslim edilen siparişler için açılabilir.'});a[i].status='İade talebi';write(ORDERS,a);res.json(a[i])});
app.delete('/api/me',auth,(req,res)=>{write(USERS,read(USERS).filter(u=>u.id!==req.user.id));write(ORDERS,read(ORDERS).filter(o=>o.userId!==req.user.id));res.json({ok:true})});
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));app.listen(PORT,'0.0.0.0',()=>console.log('LÉVAREN running on '+PORT));
